GET http://localhost:8080/task/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTlmOGQwN2I1NWVhMTM2MzQ5YmQzYSIsImlhdCI6MTY3OTUxMjc4MCwiZXhwIjoxNjc5NTk5MTgwfQ.mtT-R0iuHw68vPFhvl9-y5kXs3VxUgRuglcUZUw-9CE

